service: serverless-nestjs-api-sns

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-1
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  deploymentBucket:
    name: ${self:service}-${sls:stage}
  environment:
    SNS_TOPIC_ARN: arn:aws:sns:ap-southeast-1:000000000000:MyLocalNestJSSNSTopic

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: any
          path: /{proxy+}
      - http:
          method: any
          path: /

plugins:
  - serverless-deployment-bucket
  - serverless-offline
  - serverless-plugin-optimize
  - serverless-dotenv-plugin # Optional: if you use .env files for local development

custom:
  serverless-offline:
    httpPort: 4000
  serverless-offline-aws-proxy:
    sns: true
  sns:
    endpoint: http://localhost:4566
    region: ap-southeast-1
  optimize:
    external: ['aws-sdk'] # aws-sdk is available in the Lambda environment
  dotenv:
    path: .env.local # Optional: if you use .env files for local development